/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.ventas;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ventas v;

    public main() {
        initComponents();

        int tamAlmacen = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamanio del almacen: "));
        v = new ventas(tamAlmacen);

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistarProducto = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnVisualizar = new javax.swing.JButton();
        btnVenderProducto = new javax.swing.JButton();
        btnAgotados = new javax.swing.JButton();
        btnActualizarPrecio = new javax.swing.JButton();
        btnAumentarStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de inventarios");

        btnRegistarProducto.setBackground(new java.awt.Color(204, 255, 204));
        btnRegistarProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistarProducto.setText("Registrar Producto");
        btnRegistarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarProductoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblResp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResp.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResp, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResp, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        btnVisualizar.setBackground(new java.awt.Color(204, 255, 204));
        btnVisualizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVisualizar.setText("Visualizar Inventario");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnVenderProducto.setBackground(new java.awt.Color(204, 255, 204));
        btnVenderProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVenderProducto.setText("Vender Producto");
        btnVenderProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderProductoActionPerformed(evt);
            }
        });

        btnAgotados.setBackground(new java.awt.Color(204, 255, 204));
        btnAgotados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgotados.setText("Agotados");
        btnAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgotadosActionPerformed(evt);
            }
        });

        btnActualizarPrecio.setBackground(new java.awt.Color(204, 255, 204));
        btnActualizarPrecio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizarPrecio.setText("Actualizar Precio");
        btnActualizarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPrecioActionPerformed(evt);
            }
        });

        btnAumentarStock.setBackground(new java.awt.Color(204, 255, 204));
        btnAumentarStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAumentarStock.setText("Aumentar Stock");
        btnAumentarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistarProducto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVenderProducto)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgotados)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnActualizarPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAumentarStock))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnVisualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistarProducto)
                    .addComponent(btnVisualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVenderProducto)
                    .addComponent(btnAgotados)
                    .addComponent(btnActualizarPrecio)
                    .addComponent(btnAumentarStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarProductoActionPerformed
        // TODO add your handling code here:
        try {

            //registrar
            v.registroEst();
            lblResp.setText("Inventario registrado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnRegistarProductoActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        try {

            //visualizar
            lblResp.setText(v.visualizar());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnVenderProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderProductoActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del producto a vender: ");
            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Cantidad a vender: "));

            //vender
            lblResp.setText(v.vender(nombre, cantidad));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnVenderProductoActionPerformed

    private void btnAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgotadosActionPerformed
        // TODO add your handling code here:
        try {

            //agotados
            lblResp.setText(v.agotados());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnAgotadosActionPerformed

    private void btnActualizarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPrecioActionPerformed
        // TODO add your handling code here:
        try {

            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del producto a actualizar: ");
            double precio = Double.parseDouble(JOptionPane.showInputDialog("Nuevo Precio: "));
            //actualizar precio
            lblResp.setText(v.actualizarPrecio(nombre, precio));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnActualizarPrecioActionPerformed

    private void btnAumentarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarStockActionPerformed
        // TODO add your handling code here:
        try {

            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del producto a aumentar: ");
            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Nuevo Stock: "));
            //actualizar precio
            lblResp.setText(v.aumentarStock(nombre, cantidad));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnAumentarStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPrecio;
    private javax.swing.JButton btnAgotados;
    private javax.swing.JButton btnAumentarStock;
    private javax.swing.JToggleButton btnRegistarProducto;
    private javax.swing.JButton btnVenderProducto;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel lblResp = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
